#!/bin/sh
set -e

PACKAGE_NAME="sensorium"
PACKAGE_VERSION="@VERSION@"

if command -v dkms >/dev/null 2>&1; then
	dkms add -m "${PACKAGE_NAME}" -v "${PACKAGE_VERSION}" || true
	dkms build -m "${PACKAGE_NAME}" -v "${PACKAGE_VERSION}" || true
	dkms install -m "${PACKAGE_NAME}" -v "${PACKAGE_VERSION}" || true
fi

exit 0
