#!/usr/bin/env python3
from __future__ import annotations


RUNTIME_BRIDGE_ABI_VERSION = 5
RUNTIME_BRIDGE_FRAME_LIMIT = 262144
RUNTIME_BRIDGE_HEADER_SIZE = 32
RUNTIME_BRIDGE_SEGMENT_PAYLOAD_LIMIT = (
    RUNTIME_BRIDGE_FRAME_LIMIT - RUNTIME_BRIDGE_HEADER_SIZE
)
RUNTIME_MAX_PAYLOAD = 4 * 1024 * 1024
RUNTIME_BRIDGE_DEFAULT_CONTROL_RING_ENTRIES = 64
RUNTIME_BRIDGE_DEFAULT_TRANSPORT_RING_ENTRIES = 128
RUNTIME_BRIDGE_DEFAULT_REPLY_RING_ENTRIES = 128
RUNTIME_BRIDGE_DEFAULT_PAYLOAD_ARENA_SIZE = 8 * 1024 * 1024
RUNTIME_MAX_I2C_MSGS = 256
RUNTIME_MAX_SPI_XFERS = 256
RUNTIME_MODEL_SCHEMA_VERSION = 2
RUNTIME_SNAPSHOT_SCHEMA_VERSION = 2
RUNTIME_DAEMON_STATES = {"empty", "applying", "ready", "degraded", "desynced"}

RUNTIME_TRANSPORTS = {"i2c", "spi", "uart"}
RUNTIME_TEMPLATE_KINDS = {"i2c-register-bank", "spi-script", "uart-script"}
RUNTIME_FAULT_MODES = {"none", "timeout", "errno", "disconnect", "short-reply"}
UART_PARITY_MODES = {"none", "even", "odd"}
