obj-m += sensorium.o

sensorium-objs := \
	sensorium-camera-core.o \
	sensorium-config.o \
	sensorium-core.o \
	sensorium-transport-alias.o \
	sensorium-transport-alias-i2c.o \
	sensorium-transport-alias-spi.o \
	sensorium-transport-alias-uart.o \
	sensorium-sensor.o \
	sensorium-inject.o \
	sensorium-capture.o \
	sensorium-iio.o \
	sensorium-runtime-core.o \
	sensorium-runtime-i2c.o \
	sensorium-runtime-spi.o \
	sensorium-runtime-uart-queue.o \
	sensorium-runtime-uart-tty.o \
	sensorium-runtime-uart.o \
	sensorium-runtime-transport.o \
	sensorium-runtime.o
