#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
kernel_release="$(uname -r)"
kernel_base="${kernel_release%%-*}"
tag="${WSL_KERNEL_TAG:-linux-msft-wsl-${kernel_base}}"
work_root="${WSL_KERNEL_WORK_ROOT:-${repo_root}/.cache/wsl-kernel}"
src_root="${work_root}/${tag}"
archive_path="${work_root}/${tag}.tar.gz"
repo_url="${WSL_KERNEL_REPO_URL:-https://github.com/microsoft/WSL2-Linux-Kernel}"
archive_url="${repo_url}/archive/refs/tags/${tag}.tar.gz"
env_file="${repo_root}/.env.kernel"
jobs="${JOBS:-$(nproc)}"

need_cmd() {
	local cmd="$1"
	if ! command -v "${cmd}" >/dev/null 2>&1; then
		echo "Missing required command: ${cmd}" >&2
		exit 1
	fi
}

mkdir -p "${work_root}"

need_cmd curl
need_cmd tar
need_cmd make

if [[ ! -d "${src_root}" ]]; then
	echo "Downloading official WSL kernel source for ${tag}"
	curl -fL "${archive_url}" -o "${archive_path}"
	tar -xzf "${archive_path}" -C "${work_root}"
	mv "${work_root}/WSL2-Linux-Kernel-${tag}" "${src_root}"
fi

if [[ ! -f "${src_root}/Microsoft/config-wsl" ]]; then
	echo "Expected WSL kernel config not found in ${src_root}" >&2
	exit 1
fi

echo "Preparing kernel tree in ${src_root}"
cp "${src_root}/Microsoft/config-wsl" "${src_root}/.config"
if [[ -x "${src_root}/scripts/config" ]]; then
	"${src_root}/scripts/config" --disable IKHEADERS
fi
make -C "${src_root}" olddefconfig
make -C "${src_root}" prepare modules_prepare -j"${jobs}"

if [[ ! -f "${src_root}/Module.symvers" ]]; then
	echo
	echo "Building the configured WSL modules once to generate Module.symvers..."
	echo "This can take a while, but it only needs to succeed once per kernel tag."
	make -C "${src_root}" modules -j"${jobs}"
fi

cat >"${env_file}" <<EOF
# Auto-generated by scripts/prepare-wsl-kernel-tree.sh
export KDIR=${src_root}
export WSL_KERNEL_TAG=${tag}
EOF

echo
echo "Prepared WSL kernel tree:"
echo "  tag:  ${tag}"
echo "  KDIR: ${src_root}"
if [[ -f "${src_root}/Module.symvers" ]]; then
	echo "  symvers: ${src_root}/Module.symvers"
fi
echo
echo "Saved environment helper to ${env_file}"
echo "You can now run:"
echo "  source ${env_file}"
echo "  ./scripts/reload-sensorium.sh"
